name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 2.3
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - "3.0"
          - 3.1
          - head
          - jruby-9.1.17.0
          - "jruby-9.2.20.0"
          - jruby-9.3.3.0
        resque-version:
          - "master"
          - "~> 2.0.0"
          - "~> 1.27"
        rufus-scheduler:
          - "3.2"
          - "3.4"
          - "3.5"
          - "3.6"
        exclude:
          - ruby-version: head
            rufus-scheduler: 3.2
    env:
      RESQUE: "${{ matrix.resque-version }}"
      RUFUS_SCHEDULER: "${{ matrix.rufus-scheduler }}"
      COVERAGE: 1
      JRUBY_OPTS: ""
      RUBYOPT: "-W0"

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: true
      - run: bundle exec rake
      - run: bin/bundle_console_test.sh
